In [3]:
import cv2
import numpy as np

In [27]:
img = cv2.imread('./images/donut3.png')
# img = cv2.imread('./images/shapes_donut.jpg')
# img = cv2.imread('./images/bunchofshapes.jpg')
cv2.imshow('original image',img)
cv2.waitKey()

img_black = np.zeros(img.shape)

img_orig = img.copy()
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img_canny = cv2.Canny(img_gray,50,200)
cv2.imshow('Canny',img_canny)
cv2.waitKey()

contours,hierarchy = cv2.findContours(img_canny.copy(),cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
print ('no of countours',len(contours))
print ('Hierarchy',hierarchy)
cv2.drawContours(img_black,contours,-1,(0,255,0),3)
cv2.imshow('Contour over blank',img_black)
cv2.waitKey()

cv2.drawContours(img,contours,-1,(0,255,0),3)
cv2.imshow('Contours over image',img)
cv2.waitKey()
cv2.imshow('Oriz',img_orig)
cv2.waitKey()
cv2.destroyAllWindows()

('no of countours', 38)
('Hierarchy', array([[[ 1, -1, -1, -1],
        [ 3,  0,  2, -1],
        [-1, -1, -1,  1],
        [ 4,  1, -1, -1],
        [ 5,  3, -1, -1],
        [ 6,  4, -1, -1],
        [ 7,  5, -1, -1],
        [ 8,  6, -1, -1],
        [ 9,  7, -1, -1],
        [10,  8, -1, -1],
        [11,  9, -1, -1],
        [12, 10, -1, -1],
        [13, 11, -1, -1],
        [15, 12, 14, -1],
        [-1, -1, -1, 13],
        [16, 13, -1, -1],
        [17, 15, -1, -1],
        [18, 16, -1, -1],
        [21, 17, 19, -1],
        [-1, -1, 20, 18],
        [-1, -1, -1, 19],
        [22, 18, -1, -1],
        [23, 21, -1, -1],
        [24, 22, -1, -1],
        [25, 23, -1, -1],
        [26, 24, -1, -1],
        [27, 25, -1, -1],
        [28, 26, -1, -1],
        [29, 27, -1, -1],
        [30, 28, -1, -1],
        [31, 29, -1, -1],
        [32, 30, -1, -1],
        [33, 31, -1, -1],
        [34, 32, -1, -1],
        [35, 33, -1, -1],
        [36, 34, -1, -1],
        [37, 35, -1, -1],


In [5]:
# img = cv2.imread('./images/bunchofshapes.jpg')
# img = cv2.imread('./images/shapes_donut.jpg')
img = cv2.imread('./images/donut1.png')

def get_contour_area(contours):
    all_area=[]
    for x in contours:
        area = cv2.contourArea(x);
        all_area.append(area)
    return all_area

img_orig = img.copy()

print ('Hierarchy',hierarchy)
print ('Contour area before aorting',get_contour_area(contours))

sorted_contours = sorted(contours,key=cv2.contourArea,reverse=True)
print ('Contour area after sorting',get_contour_area(sorted_contours))

for c in sorted_contours:
    cv2.drawContours(img,[c],-1,(0,255,0),3)
    cv2.waitKey()
    cv2.imshow('Contours sorted by area',img)
cv2.waitKey()
cv2.destroyAllWindows()

('Hierarchy', array([[[ 8, -1,  1, -1],
        [-1, -1,  2,  0],
        [-1, -1,  3,  1],
        [-1, -1,  4,  2],
        [-1, -1,  5,  3],
        [-1, -1,  6,  4],
        [-1, -1,  7,  5],
        [-1, -1, -1,  6],
        [16,  0,  9, -1],
        [-1, -1, 10,  8],
        [-1, -1, 11,  9],
        [-1, -1, 12, 10],
        [-1, -1, 13, 11],
        [-1, -1, 14, 12],
        [-1, -1, 15, 13],
        [-1, -1, -1, 14],
        [24,  8, 17, -1],
        [-1, -1, 18, 16],
        [-1, -1, 19, 17],
        [-1, -1, 20, 18],
        [-1, -1, 21, 19],
        [-1, -1, 22, 20],
        [-1, -1, 23, 21],
        [-1, -1, -1, 22],
        [-1, 16, -1, -1]]], dtype=int32))
('Contour area before aorting', [2613.5, 2562.5, 2033.5, 2001.5, 275.0, 265.0, 111.0, 100.0, 7236.0, 7152.0, 5643.0, 5566.0, 754.0, 726.0, 313.5, 296.5, 25011.0, 24854.0, 22031.5, 21884.5, 6093.5, 6017.5, 4685.0, 4619.0, 0.0])
('Contour area after sorting', [25011.0, 24854.0, 22031.5, 21884.5, 7236.0, 7152.0, 6093.5, 6

In [6]:
def x_chord_contour(contours):
    if cv2.contourArea(contours)>10:
        M = cv2.moments(contours)
        return (int(M['m10']/M['m00']))
def label_contour_center(img,c):
    M = cv2.moments(c)
    cx = int(M['m10']/M['m00'])
    cy = int(M['m01']/M['m00'])
    cv2.circle(img,(cx,cy),10,(0,255,0),-1)
    # return img
# img = cv2.imread('./images/shapes_donut.jpg')
img = cv2.imread('./images/donut1.png')
img_orig = img.copy()

for c in contours:
    label_contour_center(img,c)
cv2.imshow('Centers',img)
cv2.waitKey()

contours_l_to_r = sorted(contours,key=x_chord_contour,reverse=False)

for (i,c) in enumerate(contours):
    cv2.drawContours(img_orig,[c],-1,(0,255,0),3)
    M = cv2.moments(c)
    cx = int(M['m10']/M['m00'])
    cy = int(M['m01']/M['m00'])
    cv2.putText(img_orig,str(i+1),(cx,cy),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)
    cv2.imshow('L_to_r contours',img_orig)
    cv2.waitKey()
    (x,y,w,h) = cv2.boundingRect(c)
    cropped_contour = img_orig[y:y+h,x:x+w]
    img_name = './images/output_shape_number_'+str(i+1)+'.jpg'
    cv2.imwrite(img_name,cropped_contour)
    print img_name
cv2.destroyAllWindows()

ZeroDivisionError: float division by zero

In [47]:
import cv2
import numpy as np
# img = cv2.imread('./images/shapes_donut.jpg')
img = cv2.imread('./images/donut1.png')
cv2.imshow('Original',img)
cv2.waitKey()
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('gray',img_gray)
cv2.waitKey()
kernel = np.ones((5,5),np.uint8)
img_gray = cv2.dilate(img_gray,kernel,iterations=2)
# img_gray = cv2.dilate(img_gray,kernel,iterations=1)
img_orig = img.copy()
cv2.imshow('gray erode',img_gray)
cv2.waitKey()
img_canny = cv2.Canny(img_gray,50,200)
cv2.imshow('Canny',img_canny)
cv2.waitKey()
contours,hierarchy = cv2.findContours(img_canny.copy(),cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
print('contours length',len(contours))
# print hierarchy
imgg=img.copy()
cv2.drawContours(imgg,contours,-1,(0,255,0),2)
cv2.imshow('image with contours',imgg)
cv2.waitKey()
# print contours
new_contours=[]
new_hierarchy=[]
x=0
while x!=-1:
    print('x ',x)
    a1=cv2.contourArea(contours[x])
    print('a1 ',a1)
    c1=hierarchy[0][x][2]
    a2=0;
    if c1!=-1:
        a2=cv2.contourArea(contours[c1])
        print('a2 ',a2)
    # if (a1-a2)<=20:
    hierarchy[0][x][2]=hierarchy[0][c1][2]
# print(a1," ",a2)
    new_contours.append(contours[x])
    new_hierarchy.append(hierarchy[0][x].tolist())
    x=hierarchy[0][x][0]
# print new_contours
print hierarchy
print new_hierarchy
# newh = list()
# newh.append(new_hierarchy)
# print newh[0]
# cv2.drawContours(img,new_contours,-1,(0,255,0),2)
# cv2.imshow('image with contours',img)
# cv2.waitKey()
def sortalgo(ch):
    c,h=ch
    a1=cv2.contourArea(c)
    a2=0
    if h[2]!=-1:
        a2=cv2.contourArea(contours[h[2]])
    # print (a1-a2)
    print (a1," ",a2)
    return a1-a2
sc = [x for x,_ in sorted(zip(new_contours,new_hierarchy),key=sortalgo,reverse=False)]
#     cv2.waitKey()
for (i,c) in enumerate(sc):
    cv2.drawContours(img,[c],-1,(0,255,0),3)
    if new_hierarchy[i][2]!=-1:
        cv2.drawContours(img,[contours[new_hierarchy[i][2]]],-1,(0,255,0),3)
    cv2.waitKey()
    cv2.imshow('Contours sorted by area',img)
cv2.waitKey()
cv2.destroyAllWindows()

('contours length', 12)
('x ', 0)
('a1 ', 1778.0)
('a2 ', 1738.0)
('x ', 4)
('a1 ', 5837.5)
('a2 ', 5771.5)
('x ', 8)
('a1 ', 22342.0)
('a2 ', 22210.0)
[[[ 4 -1  2 -1]
  [-1 -1  2  0]
  [-1 -1  3  1]
  [-1 -1 -1  2]
  [ 8  0  6 -1]
  [-1 -1  6  4]
  [-1 -1  7  5]
  [-1 -1 -1  6]
  [-1  4 10 -1]
  [-1 -1 10  8]
  [-1 -1 11  9]
  [-1 -1 -1 10]]]
[[4, -1, 2, -1], [8, 0, 6, -1], [-1, 4, 10, -1]]
(1778.0, ' ', 351.5)
(5837.5, ' ', 664.5)
(22342.0, ' ', 5865.5)
